.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */

.section .text

.align 4

/* Generated by spimdisasm 1.33.0 */

glabel test # 0
    /* 0000B0 000000B0 A0850000 */  sb          $a1, 0x0($a0)
    /* 0000B4 000000B4 03E00008 */  jr          $ra
    /* 0000B8 000000B8 A4860002 */   sh         $a2, 0x2($a0)
.size test, . - test
    /* 0000BC 000000BC 00000000 */  nop
