.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */

.section .text

.align 4

/* Generated by spimdisasm 1.33.0 */

glabel test # 0
    /* 0000B0 000000B0 AFA60008 */  sw          $a2, 0x8($sp)
    /* 0000B4 000000B4 8CA20000 */  lw          $v0, 0x0($a1)
    /* 0000B8 000000B8 30CE00FF */  andi        $t6, $a2, 0xFF
    /* 0000BC 000000BC 244F0001 */  addiu       $t7, $v0, 0x1
    /* 0000C0 000000C0 29E10028 */  slti        $at, $t7, 0x28
    /* 0000C4 000000C4 10200005 */  beqz        $at, .L000000DC
    /* 0000C8 000000C8 0082C021 */   addu       $t8, $a0, $v0
    /* 0000CC 000000CC A30E0000 */  sb          $t6, 0x0($t8)
    /* 0000D0 000000D0 8CB90000 */  lw          $t9, 0x0($a1)
    /* 0000D4 000000D4 27280001 */  addiu       $t0, $t9, 0x1
    /* 0000D8 000000D8 ACA80000 */  sw          $t0, 0x0($a1)
  .L000000DC:
    /* 0000DC 000000DC 03E00008 */  jr          $ra
    /* 0000E0 000000E0 00000000 */   nop
.size test, . - test
    /* 0000E4 000000E4 00000000 */  nop
    /* 0000E8 000000E8 00000000 */  nop
    /* 0000EC 000000EC 00000000 */  nop
